### ISSUE TITLE
Basic example of how to use this lib?

### ISSUE THREAD

**Issue by janus190** [Cu3PO42/NTRClientJS#1]
Hey there, thanks for making this lib! I was wondering if you could throw up a basic example of how to use the NTRClient? I'm happy to see a client that doesn't use Windows, however JS is not exactly my strong suit. A quick example showing:
1. Connecting to NTR debugger via N3DS IP
2. Getting the process id (`pid`) from a game's title id
3. Reading a 16bit value at certain offset

Sorry if I'm troubling your time but if you could just hack something together that would be great point for me to start!

**Comment by Cu3PO42** [comment]
Unfortunately I am in the middle of exams right now and can't really write something new, however I use this library in another project. I used [this gist](https://gist.github.com/Cu3PO42/a25f458d6a784bc4762ed917b132853f) to debug some issues someone had, it contains the three things you asked about :)

**Comment by janus190** [comment]
Thanks, I'll take a look... been a while since I've touched JS, gotta get familiar with ES6 stuff.

All the best with your exams!
